(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'add_home_slide_resource_validator' is not defined"
p3
sS'layer'
p4
S'/home/filhofilha/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/manager.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n\n\n\n\n@auth.requires_login()\ndef index():\n\n    return dict()\n\n\n\n@auth.requires_login()\ndef home_slide_resources():\n\n    return dict(mRows=db(db.tbHomePageSlideResources.id>0).select())\n\n\n@auth.requires_login()\ndef add_home_slide_resource():\n\n    mForm = SQLFORM(db.tbHomePageSlideResources, submit_button=T(\'Submit\'))\n\n    Validator().form_process(mForm, URL("manager", "home_slide_resources"), mValidation=add_home_slide_resource_validator)\n\n    return dict(mForm=mForm)\n\ndef add_home_slide_resource_accepted(mForm):\n    print mForm.vars.id\n\n    pass\n\n\ndef download():\n    return response.download(request, db)\n\nresponse._vars=response._caller(add_home_slide_resource)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/filhofilha/Documents/Deployment/Web2Py/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/filhofilha/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/manager.py", line 38, in <module>\n  File "/home/filhofilha/Documents/Deployment/Web2Py/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/filhofilha/Documents/Deployment/Web2Py/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/home/filhofilha/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/manager.py", line 25, in add_home_slide_resource\n    Validator().form_process(mForm, URL("manager", "home_slide_resources"), mValidation=add_home_slide_resource_validator)\nNameError: global name \'add_home_slide_resource_validator\' is not defined\n'
p11
s.